# Generated by Django 4.2.2 on 2023-06-26 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9bbb7383-f778-467e-bd7e-a92ecf13b69a'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('descreption', models.TextField(blank=True, max_length=500, null=True)),
                ('prise', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('img', models.ImageField(default='static/images/placeholder/img.png', upload_to='static/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
