# Generated by Django 4.2.2 on 2023-06-26 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(default=uuid.UUID('660a565d-148b-4412-beab-504c031166a3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
