# Generated by Django 4.2.2 on 2023-06-15 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='descreption',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(default='static/images/placeholder/img.png', upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='prise',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0c68dc8-864b-4ff0-9114-bb671a81065a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
