# Generated by Django 4.2.2 on 2023-06-15 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_descreption_products_img_products_prise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca696359-812c-4eee-a873-a48ad55740a3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
