# Generated by Django 4.2.2 on 2023-06-20 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c3e9d898-1af6-4da8-ada0-42579e75b5d3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
