# Generated by Django 4.2.2 on 2023-06-23 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d92cd6d-bdfa-4783-8d41-5b5b62c811bc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
