# Generated by Django 4.2.2 on 2023-06-25 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(default=uuid.UUID('db200886-d98b-4510-8028-f91194c673a2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
